import type { OfficialMinyan } from "@/lib/types";

export const officialMinyanim: OfficialMinyan[] = [
  {
    id: "m-101",
    tefillah: "mincha",
    name: "Mincha Minyan",
    shulName: "Beit Knesset Ramban",
    lat: 31.7683,
    lng: 35.23,
    address: "5 Ramban St, Jerusalem",
    reliability: 95,
    members: 9,
    startTime: "3:05 PM",
  },
  {
    id: "m-102",
    tefillah: "shacharis",
    name: "Morning Minyan",
    shulName: "Shir Chadash",
    lat: 31.772,
    lng: 35.218,
    address: "12 Derech Bethlehem, Jerusalem",
    reliability: 88,
    members: 7,
    startTime: "7:30 AM",
  },
  {
    id: "m-103",
    tefillah: "maariv",
    name: "Maariv Minyan",
    shulName: "Baka Community Shul",
    lat: 31.7595,
    lng: 35.2142,
    address: "8 Baka Rd, Jerusalem",
    reliability: 90,
    members: 6,
    startTime: "8:20 PM",
  },
  {
    id: "m-104",
    tefillah: "mincha",
    name: "Early Mincha",
    shulName: "Nachlaot Beit Knesset",
    lat: 31.7811,
    lng: 35.2168,
    address: "4 Bezalel St, Jerusalem",
    reliability: 92,
    members: 8,
    startTime: "2:50 PM",
  },
  {
    id: "m-105",
    tefillah: "shacharis",
    name: "Late Shacharis",
    shulName: "Talbiya Shul",
    lat: 31.7736,
    lng: 35.2126,
    address: "18 Jabotinsky St, Jerusalem",
    reliability: 86,
    members: 5,
    startTime: "8:25 AM",
  },
  {
    id: "m-106",
    tefillah: "maariv",
    name: "Late Maariv",
    shulName: "German Colony Shul",
    lat: 31.7578,
    lng: 35.2173,
    address: "20 Emek Refaim St, Jerusalem",
    reliability: 89,
    members: 7,
    startTime: "9:05 PM",
  },
];
